; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

[env]
; lib_deps = 
;   ; name-based (built-in library in framework)
;   SPI	; SPI
;   ; TaskScheduler > 3.7.0
;   https://github.com/arkhipenko/TaskScheduler.git
  
monitor_speed = 115200
monitor_filters = 
	colorize
	time
	send_on_enter
monitor_echo = yes
;monitor_eol = CR
